databases:
  - name: somera-db
    databaseName: somera_production
    user: somera_admin
    plan: free
































services:
  - type: web
    name: somera-bakes
    env: docker
    plan: free
    region: oregon
    startCommand: "export APP_KEY=$(php artisan key:generate --show --no-ansi) && php artisan migrate --force && apache2-foreground"
    envVars:
      - key: APP_NAME
        value: "Somera Bakes"
      - key: APP_ENV
        value: production
        
      - key: APP_DEBUG
        value: "true"
