databases:
  - name: somera-db
    databaseName: somera_production
    user: somera_admin
    plan: free








services:
  - type: web
    name: somera-bakes
    env: docker
    plan: free
    region: oregon
    startCommand: "php artisan migrate --force && apache2-foreground"
    envVars:
      - key: APP_NAME
        value: "Somera Bakes"
      - key: APP_ENV
        value: production
        
      - key: APP_DEBUG
        value: "true"
      - key: LOG_CHANNEL
        value: errorlog
      - key: APP_KEY
        value: "base64:eFeKUex8iqwcJfjlIVxDy/KF8R8jGstwPHfgUZfICJ0="
      - key: APP_URL
        value: "https://somera-bakes.onrender.com"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: somera-db
          property: host
