databases:
  - name: somera-db
    databaseName: somera_production
    user: somera_admin
    plan: free




services:
  - type: web
    name: somera-bakes
    env: php
    plan: free
    buildCommand: "./build.sh"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_NAME
        value: "Somera Bakes"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: "https://somera-bakes.onrender.com"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: somera-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: somera-db
          property: port
      - key: DB_DATABASE
